name: release

on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  build:
    name: Dispatch rgbds-live
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        env:
          VERSION: ${{ github.event.release.tag_name }}
          # owner of the repo: would be gbdev
          OWNER: SelvinPL
          # dest repo: would be rgbds-live
          REPO: projectx_using
          # GH_TOKEN has action read-write in dest repo
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run autoupdate.yml --repo ${{env.OWNER}}/${{env.REPO}} --field version=${{env.VERSION}}
          
