name: release

on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  build:
    name: Dispatch rgbds-live
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/github-script@v7
      #   env:
      #     VERSION: ${{ github.event.release.tag_name }}
      #     # owner of the repo: would be gbdev
      #     OWNER: SelvinPL
      #     # dest repo: would be rgbds-live
      #     REPO: projectx_using
      #   with:
      #     # DISPATCH_PAT - PAT with Contents read-write in dest repo(rgbds-live)
      #     github-token: ${{ secrets.DISPATCH_PAT }}
      #     script: |
      #       const client_payload = {"version": `${process.env.VERSION}` };
      #       const owner = `${process.env.OWNER}`;
      #       const repo = `${process.env.REPO}`;
      #       const result = await github.rest.repos.createDispatchEvent({
      #         owner: owner,
      #         repo: repo,
      #         event_type: 'rgbds_release',
      #         client_payload: client_payload
      #       });
      - name: Dispatch workflow
        env:
          VERSION: ${{ github.event.release.tag_name }}
          # owner of the repo: would be gbdev
          OWNER: SelvinPL
          # dest repo: would be rgbds-live
          REPO: projectx_using
        run: |
          gh auth login --with-token ${{ secrets.DISPATCH_PAT }}
          gh workflow run autoupdate.yml --repo ${{env.OWNER}}/${{env.REPO}} --field version=${{env.VERSION}}
          
