name: release

on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  build:
    name: Dispatch rgbds-live
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DISPATCH_PAT }}
          script: |
            console.log("${{github.event.release.tag_name}}")
            const result = await github.rest.repos.createDispatchEvent({
              owner: 'SelvinPL',
              repo: 'projectx_using',
              event_type: 'rgbds_release',
              client_payload: {"version": "${{github.event.release.tag_name}}" }
            })
            console.log(result);.